---

# PiCamera options.
picamera: 
    # Where to store taken pictures.
    photo_directory: "/home/pi/pimaton_pictures"
    number_of_pictures_to_take: 6
    time_before_first_picture: 2
    time_between_pictures: 1
    # Prefix for the name of the taken pictures.
    picture_prefix_name: "test_pimaton"
    # Prefix for the generated image.
    generated_prefix_name: "pimaton"

# Pimaton global options.
pimaton: 
    time_between_loop: 2

# Image options.
image:
    print_pic:
        # Path for the template jpg to use if any. 
        # Put empty string if no template.
        template: "./assets/templates/Blank.tpl.jpg"
        # Directory where are stored the generated pictures.
        output_dir: "/home/pi/pimaton_pictures"
        # Width and Height of the generated image.
        width: 1241
        height: 1754
        # Columns and Rows for the generated image.
        rows: 3
        cols: 2

    # Thumbnails size.
    thumbnails: 
        width: 560
        height: 496
